### ISSUE TITLE
Supporting class or other attributes while rendering

### ISSUE THREAD

**Issue by navidadelpour** [contentful/rich-text-renderer.py#19]
I'm using [Semantic UI](https://semantic-ui.com/) which styles every header element with `ui header` classes.

## Current behavior:
Right now, the rendered HTML is something like this. The header doesn't have any styling.
```html
<h1>Bad styled title</h>
```

## Expected behavior:
Having custom classes assigned to elements for properly styling them.
```html
<h1 class="ui header">Cool big title</h>
```
---

## P.S.
I would like to submit a pull request for this feature :smile: . We can extend the `BaseBlockRenderer.render` method to render custom attributes. these attributes can be defined just like `HeadingOneRenderer._render_tag`.

**Comment by rubydog** [comment]
@navidadelpour Let me know if you want to discuss about the code changes needed to achieve this behaviour.

**Comment by navidadelpour** [comment]
Hi @rubydog, sorry for the late response.

I was thinking about this and came across another solution (#25).

Please let me know how do you think about it.

**Comment by navidadelpour** [comment]
@rubydog Any updates on this?

**Comment by rubydog** [comment]
@navidadelpour Checking, will try to give you an update by next week.

**Comment by rubydog** [comment]
@navidadelpour, one way to achieve the behavior you are looking for is by using custom heading blocks and tweaking the rendering method from the base block renderer. Check out this snippet:

```
class SemanticUIHeadingOneRenderer < BaseBlockRenderer
  def render(node)
    "<h1 class=\"ui header\">#{render_content(node)}</h1>"
  end
end
```

What this does is create a custom renderer specifically for heading one block. It inherits from the BaseBlockRenderer and overrides the render method to add your own styling.

Hope that helps clarify things! Let me know if you have any questions.

**Comment by navidadelpour** [comment]
@rubydog Thanks for checking. Yes that's exactly what I did in my PR. I did it in the BaseBlockRenderer so that it would be easier to add any kind of attributes to it.

**Comment by rubydog** [comment]
@navidadelpour I don't feel the need to modify the gem to support a specific use case that could be accomplished through other means. Is there a compelling argument for altering the gem's functionality?

**Comment by navidadelpour** [comment]
@rubydog Correct. I'll close it then.
